namespace ColorMixer.Models;

public static class PaintDatabase
{
    // ── Peintures opaques ────────────────────────────────────────────────────
    public static List<PaintBrand> OpaqueBrands { get; } = new()
    {
        new PaintBrand { Name = "Vallejo", Mode = PaintMode.Opaque, Colors = new()
        {
            new() { Name = "Dead White",        Hex = "#F5F5F5" },
            new() { Name = "Ivory",             Hex = "#F5F0DC" },
            new() { Name = "Lemon Yellow",      Hex = "#FFF44F" },
            new() { Name = "Sun Yellow",        Hex = "#FFC200" },
            new() { Name = "Deep Yellow",       Hex = "#FFB300" },
            new() { Name = "Orange",            Hex = "#FF6B1A" },
            new() { Name = "Vermillion",        Hex = "#E34234" },
            new() { Name = "Scarlet",           Hex = "#FF2400" },
            new() { Name = "Carmine Red",       Hex = "#960018" },
            new() { Name = "Rose",              Hex = "#FF66CC" },
            new() { Name = "Magenta",           Hex = "#CF1C8B" },
            new() { Name = "Violet",            Hex = "#7F00FF" },
            new() { Name = "Royal Purple",      Hex = "#4B0082" },
            new() { Name = "Ultramarine",       Hex = "#3F00FF" },
            new() { Name = "Prussian Blue",     Hex = "#003153" },
            new() { Name = "Azure",             Hex = "#0080FF" },
            new() { Name = "Sky Blue",          Hex = "#87CEEB" },
            new() { Name = "Turquoise",         Hex = "#00CED1" },
            new() { Name = "Intermediate Grn",  Hex = "#007940" },
            new() { Name = "Emerald",           Hex = "#50C878" },
            new() { Name = "Lime Green",        Hex = "#32CD32" },
            new() { Name = "Yellow Green",      Hex = "#9ACD32" },
            new() { Name = "Khaki",             Hex = "#C3B091" },
            new() { Name = "Raw Sienna",        Hex = "#C68642" },
            new() { Name = "Burnt Sienna",      Hex = "#8B4513" },
            new() { Name = "Chocolate Brown",   Hex = "#3D1C02" },
            new() { Name = "Neutral Grey",      Hex = "#8B8B8B" },
            new() { Name = "Black",             Hex = "#0D0D0D" },
        }},
        new PaintBrand { Name = "Citadel", Mode = PaintMode.Opaque, Colors = new()
        {
            new() { Name = "White Scar",        Hex = "#F8F8F8" },
            new() { Name = "Flash Gitz Yellow", Hex = "#FFE01B" },
            new() { Name = "Yriel Yellow",      Hex = "#FFBD00" },
            new() { Name = "Troll Slayer Org",  Hex = "#FF4F00" },
            new() { Name = "Evil Sunz Scarlet", Hex = "#C60000" },
            new() { Name = "Wild Rider Red",    Hex = "#E52B21" },
            new() { Name = "Mephiston Red",     Hex = "#9A0A0A" },
            new() { Name = "Pink Horror",       Hex = "#E94592" },
            new() { Name = "Screamer Pink",     Hex = "#8C1551" },
            new() { Name = "Xereus Purple",     Hex = "#5C0078" },
            new() { Name = "Daemonette Hide",   Hex = "#735980" },
            new() { Name = "Kantor Blue",       Hex = "#010F5A" },
            new() { Name = "Macragge Blue",     Hex = "#1A3BB3" },
            new() { Name = "Caledor Sky",       Hex = "#2B6FB3" },
            new() { Name = "Lothern Blue",      Hex = "#3C8AC4" },
            new() { Name = "Sotek Green",       Hex = "#1E7661" },
            new() { Name = "Temple Guard Blue", Hex = "#2D9C87" },
            new() { Name = "Moot Green",        Hex = "#1EC500" },
            new() { Name = "Warpstone Glow",    Hex = "#10A030" },
            new() { Name = "Straken Green",     Hex = "#4D6B2A" },
            new() { Name = "Averland Sunset",   Hex = "#E9A024" },
            new() { Name = "Zandri Dust",       Hex = "#A89060" },
            new() { Name = "XV-88",             Hex = "#7A5C34" },
            new() { Name = "Rhinox Hide",       Hex = "#422318" },
            new() { Name = "Mechanicus Grey",   Hex = "#545454" },
            new() { Name = "Eshin Grey",        Hex = "#3A3A40" },
            new() { Name = "Abaddon Black",     Hex = "#070707" },
        }},
        new PaintBrand { Name = "Liquitex", Mode = PaintMode.Opaque, Colors = new()
        {
            new() { Name = "Titanium White",    Hex = "#FEFEFE" },
            new() { Name = "Hansa Yellow Lt",   Hex = "#FFEC6E" },
            new() { Name = "Cadmium Yellow Md", Hex = "#FFA400" },
            new() { Name = "Cadmium Orange",    Hex = "#FF4E00" },
            new() { Name = "Cadmium Red Md",    Hex = "#D61D12" },
            new() { Name = "Naphthol Crimson",  Hex = "#B90022" },
            new() { Name = "Quinacridone Red",  Hex = "#E91060" },
            new() { Name = "Quinacridone Mag",  Hex = "#CC2060" },
            new() { Name = "Dioxazine Purple",  Hex = "#3B0760" },
            new() { Name = "Prism Violet",      Hex = "#5B1F8A" },
            new() { Name = "Cobalt Blue",       Hex = "#0047AB" },
            new() { Name = "Ultramarine Blue",  Hex = "#1F31AE" },
            new() { Name = "Cerulean Blue",     Hex = "#2A52BE" },
            new() { Name = "Phthalocya. Blue",  Hex = "#000F89" },
            new() { Name = "Phthalocya. Green", Hex = "#00A896" },
            new() { Name = "Viridian",          Hex = "#40826D" },
            new() { Name = "Hooker's Green",    Hex = "#1B4D3E" },
            new() { Name = "Sap Green",         Hex = "#4A7C59" },
            new() { Name = "Yellow Oxide",      Hex = "#C8900A" },
            new() { Name = "Raw Sienna",        Hex = "#C68642" },
            new() { Name = "Burnt Sienna",      Hex = "#8B4513" },
            new() { Name = "Raw Umber",         Hex = "#826644" },
            new() { Name = "Burnt Umber",       Hex = "#5C3317" },
            new() { Name = "Mars Black",        Hex = "#181818" },
            new() { Name = "Payne's Gray",      Hex = "#40404F" },
        }},
    };

    // ── Aquarelles ───────────────────────────────────────────────────────────
    public static List<PaintBrand> WatercolorBrands { get; } = new()
    {
        // ── Mijello Mission Gold ─────────────────────────────────────────────
        new PaintBrand { Name = "Mijello", Mode = PaintMode.Watercolor, Colors = new()
        {
            new() { Name = "Lemon Yellow",        Hex = "#FFF44F", PigmentCode = "PY3",      IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Permanent Yellow",    Hex = "#FFD700", PigmentCode = "PY74",     IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Yellow Ochre",        Hex = "#C8960C", PigmentCode = "PY43",     IsTransparent = false, IsGranulating = true,  IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Gold Ochre",          Hex = "#D4900A", PigmentCode = "PY42",     IsTransparent = false, IsGranulating = true,  IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Permanent Orange",    Hex = "#FF6B1A", PigmentCode = "PO62",     IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Vermilion",           Hex = "#E34234", PigmentCode = "PR255",    IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Scarlet Lake",        Hex = "#FF2400", PigmentCode = "PR188",    IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.22 },
            new() { Name = "Crimson Lake",        Hex = "#990020", PigmentCode = "PR83",     IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.25 },
            new() { Name = "Permanent Carmine",   Hex = "#B80040", PigmentCode = "PR176",    IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.22 },
            new() { Name = "Rose Madder",         Hex = "#E8006A", PigmentCode = "PV19",     IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.25 },
            new() { Name = "Quinacridone Magenta",Hex = "#CC2060", PigmentCode = "PR122",    IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.25 },
            new() { Name = "Violet",              Hex = "#6A0DAD", PigmentCode = "PV23",     IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.28 },
            new() { Name = "Ultramarine Deep",    Hex = "#1010C8", PigmentCode = "PB29",     IsTransparent = true,  IsGranulating = true,  IsStaining = false, DryingFactor = 0.25 },
            new() { Name = "French Ultramarine",  Hex = "#1A1AE0", PigmentCode = "PB29",     IsTransparent = true,  IsGranulating = true,  IsStaining = false, DryingFactor = 0.25 },
            new() { Name = "Cobalt Blue",         Hex = "#0047AB", PigmentCode = "PB28",     IsTransparent = true,  IsGranulating = true,  IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Cerulean Blue",       Hex = "#2A8CC0", PigmentCode = "PB35",     IsTransparent = false, IsGranulating = true,  IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Phthalo Blue",        Hex = "#00408C", PigmentCode = "PB15:3",   IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.30 },
            new() { Name = "Prussian Blue",       Hex = "#003153", PigmentCode = "PB27",     IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.28 },
            new() { Name = "Phthalo Green",       Hex = "#00765A", PigmentCode = "PG7",      IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.30 },
            new() { Name = "Sap Green",           Hex = "#4A7C59", PigmentCode = "PY150/PG7",IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.25 },
            new() { Name = "Raw Sienna",          Hex = "#C68642", PigmentCode = "PBr7",     IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Burnt Sienna",        Hex = "#8B4513", PigmentCode = "PBr7",     IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Burnt Umber",         Hex = "#5C3317", PigmentCode = "PBr7",     IsTransparent = false, IsGranulating = true,  IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Sepia",               Hex = "#3D2010", PigmentCode = "NBk/PBr7", IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.25 },
            new() { Name = "Payne's Gray",       Hex = "#40404F", PigmentCode = "PBk6/PB29",IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.25 },
            new() { Name = "Ivory Black",         Hex = "#1C1C1C", PigmentCode = "PBk9",     IsTransparent = false, IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
        }},

        // ── Daler-Rowney Artists' Watercolour ───────────────────────────────
        new PaintBrand { Name = "Daler-Rowney", Mode = PaintMode.Watercolor, Colors = new()
        {
            new() { Name = "Lemon Yellow",        Hex = "#FFF44F", PigmentCode = "PY175",    IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Cadmium Yellow Pale", Hex = "#FFE066", PigmentCode = "PY35",     IsTransparent = false, IsGranulating = false, IsStaining = false, DryingFactor = 0.15 },
            new() { Name = "Yellow Ochre",        Hex = "#C8960C", PigmentCode = "PY43",     IsTransparent = false, IsGranulating = true,  IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Raw Sienna",          Hex = "#C68642", PigmentCode = "PBr7",     IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Gold",                Hex = "#D4A017", PigmentCode = "PY42/PY43",IsTransparent = false, IsGranulating = true,  IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Cadmium Orange",      Hex = "#FF6B1A", PigmentCode = "PO20",     IsTransparent = false, IsGranulating = false, IsStaining = false, DryingFactor = 0.15 },
            new() { Name = "Cadmium Red",         Hex = "#CC2200", PigmentCode = "PR108",    IsTransparent = false, IsGranulating = false, IsStaining = false, DryingFactor = 0.15 },
            new() { Name = "Cadmium Red Deep",    Hex = "#990000", PigmentCode = "PR108",    IsTransparent = false, IsGranulating = false, IsStaining = false, DryingFactor = 0.15 },
            new() { Name = "Alizarin Crimson",    Hex = "#960018", PigmentCode = "PR83",     IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.25 },
            new() { Name = "Permanent Rose",      Hex = "#FF007F", PigmentCode = "PV19",     IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.25 },
            new() { Name = "Permanent Mauve",     Hex = "#884DA7", PigmentCode = "PV16",     IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.22 },
            new() { Name = "Purple Lake",         Hex = "#6A0DAD", PigmentCode = "PV23",     IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.28 },
            new() { Name = "French Ultramarine",  Hex = "#1A1AE0", PigmentCode = "PB29",     IsTransparent = true,  IsGranulating = true,  IsStaining = false, DryingFactor = 0.25 },
            new() { Name = "Cobalt Blue",         Hex = "#0047AB", PigmentCode = "PB28",     IsTransparent = true,  IsGranulating = true,  IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Cerulean Blue",       Hex = "#2A8CC0", PigmentCode = "PB35",     IsTransparent = false, IsGranulating = true,  IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Prussian Blue",       Hex = "#003153", PigmentCode = "PB27",     IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.28 },
            new() { Name = "Indigo",              Hex = "#1B1464", PigmentCode = "PB60/PBk6",IsTransparent = true,  IsGranulating = false, IsStaining = true,  DryingFactor = 0.25 },
            new() { Name = "Viridian",            Hex = "#40826D", PigmentCode = "PG18",     IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Hooker's Green",     Hex = "#1B4D3E", PigmentCode = "PG7/PY3",  IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.22 },
            new() { Name = "Sap Green",           Hex = "#4A7C59", PigmentCode = "PY150/PG7",IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.25 },
            new() { Name = "Burnt Sienna",        Hex = "#8B4513", PigmentCode = "PBr7",     IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Burnt Umber",         Hex = "#5C3317", PigmentCode = "PBr7",     IsTransparent = false, IsGranulating = true,  IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Raw Umber",           Hex = "#826644", PigmentCode = "PBr7",     IsTransparent = false, IsGranulating = true,  IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Vandyke Brown",       Hex = "#4A2C0A", PigmentCode = "PBr8",     IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
            new() { Name = "Payne's Gray",       Hex = "#40404F", PigmentCode = "PBk6/PB29",IsTransparent = true,  IsGranulating = false, IsStaining = false, DryingFactor = 0.25 },
            new() { Name = "Ivory Black",         Hex = "#1F1F1F", PigmentCode = "PBk9",     IsTransparent = false, IsGranulating = false, IsStaining = false, DryingFactor = 0.20 },
        }},
    };

    // ── Accès unifié selon le mode ────────────────────────────────────────────
    public static List<PaintBrand> GetBrands(PaintMode mode) =>
        mode == PaintMode.Watercolor ? WatercolorBrands : OpaqueBrands;
}
